//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerador_de_Folha_de_Pagamento_Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MATHEUS-C5\\SQLEXPRESS;Initial Catalog=Acesso_Ataron;Integrated Securi" +
            "ty=True")]
        public string Acesso_AtaronConnectionString {
            get {
                return ((string)(this["Acesso_AtaronConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MATHEUS-C5\\SQLEXPRESS;Initial Catalog=Folha_Pagamento_Ataron;Integrat" +
            "ed Security=True")]
        public string Folha_Pagamento_Ataron_Funcionario_ConnectionString {
            get {
                return ((string)(this["Folha_Pagamento_Ataron_Funcionario_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Folha_Pagamento_Ataron.mssql.somee.com;Initial Catalog=Folha_Pagament" +
            "o_Ataron;User ID=matheusc5_SQLLogin_4;Password=wm6ibg2BpCEmNc9")]
        public string Folha_Pagamento_AtaronConnectionString {
            get {
                return ((string)(this["Folha_Pagamento_AtaronConnectionString"]));
            }
        }
    }
}
